
spring:
  datasource:
# mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://TEST
    username: test
    password: test
  batch:
    job:
      name: MY_BATIS_ITEM_WRITER # 실행 job 명 셋팅 MYBATIS_CHUNK_JOB, MY_BATIS_ITEM_WRITER
    # H2 DataBase
  # H2 Setting Info
  #h2:
  #  console:
  #    enabled: true  # H2 Console
  #    path: /h2-console  # H2 Console Path
  # Database Setting Inf
  #datasource:
  #  hikari:
  #    maximum-pool-size: 10
  #    username: sa
  #    password: password
  #  url: jdbc:h2:mem:testdb
  #  driver-class-name: org.h2.Driver
  # batch meta-table create
  #batch:
  #  jdbc:
  #    initialize-schema: always
    # sql
    #url: jdbc:hsqldb:mem:testdb
    #driver-class-name: org.hsqldb.jdbc.JDBCDriver

    #apache derby
    #url: jdbc:derby:memory:testdb;create=true
    #driver-class-name: org.apache.derby.jdbc.EmbeddedDriver


